Добавляет класс действий
htmlacademy-yii/429879-task-force-1 pull request #2
Opened 2019-10-25 17:06 UTC by Deepsick

2019-10-27 21:08 UTC, kostromich requested changes
Статусы, действия и роли лучше сделать публичными константами соответствующих классов.
Тогда мы сможем обращаться к ним извне таким образом: Class::CONST1

Названия статусов лучше отделить от значений констант.

Можно заморочиться по-полной и сделать отдельный класс для каждой роли, статуса и действия.

2019-10-27 21:08 UTC, kostromich commented on classes/Actions/Actions.php
> +  private static $ROLES = ['customer', 'perfomer'];
Можем вынести роли в отдельный класс?

2019-10-27 21:08 UTC, kostromich commented on classes/Actions/Actions.php
> +  private static $STATUSES = ['Новое', 'Выполнено', 'Провалено', 'Отменено', 'В работе'];
Статусы будут лучше смотреться в отдельном классе

2019-10-27 21:08 UTC, kostromich commented on classes/Actions/Actions.php
> +  private static $actionToStatus = [
Логику переходов можно также вынести в отдельный класс, который будет управлять задачами. А можно и не выносить.

Карта переходов должна содержать исходный статус -> действие -> новый статус
Такая структура хорошо ложится в ассоциативный массив.

2019-10-27 21:08 UTC, kostromich commented on classes/Actions/Actions.php
> +  public function __construct(string $performerId, string $customerId, string $dueDate, string $activeStatus)
Поправим терминологию?
Исполнитель в контексте работы по найму должен быть переведён как `contractor`

Статус нам точно нужен?

2019-10-27 21:08 UTC, kostromich commented on classes/Actions/Actions.php
> +    $this->dueDate = $dueDate;
Тут, наверное, дедлайн?

2019-12-05 17:05 UTC, tebazil commented on src/Task.php
> +    protected static $taskActionApplyId = 'TASK_ACTION_APPLY';
Обычно сами действия стоит обозначить константами, т.е. типа 
```php
const TASK_ACTION_APPLY = 'TASK_ACTION_APPLY'
```

...

Потом текстовые названия можно сделать например так:

```php
const TASK_NAMES = [
   self::TASK_ACTION_APPLY => 'Подать заявку'
...
];
```

Так будет гораздо меньше путаницы наверху.

2019-12-05 17:05 UTC, tebazil commented on src/Task.php
> +    protected static $taskActionCompleteId = 'TASK_ACTION_COMPLETE';
Префиксы TASK_ тут не нужны... потому что из класса вызывается как self::ACTION_CANCEL - понятно, что это... а извне - Task::ACTION_CANCEL - снова понятно что это.

2019-12-05 17:05 UTC, tebazil commented on src/Task.php
> +        string $activeStatusId = 'TASK_STATUS_NEW'
Статусу лучше не давать значение по умолчанию. Это достаточно серьёзный параметр, его нужно бы указать явно извне.
И лучше использовать для этого константу, а не её значение, потому что она автокомплитится, и вероятность ошибки меньше.

2019-12-05 17:05 UTC, tebazil commented on src/TaskTest.php
> +class TaskTest extends TestCase
Тесты проходят, это класс!

2019-12-06 09:46 UTC, merged